server:
  port: 8888

spring:
  profiles:
    active: native # for local configuration

    application:
      name: config-server

    cloud:
      config:
        server:
            native:
                search-locations: classpath:/configurations # local configuration location
  config:
    import: optional:configserver:http://localhost:8888